# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170823_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acuityID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='acuityKey',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
